data_sets:
    - name: SRR5860570
      paired: True
      path: FASTQs/otherSec/SRR5860570/
      experimental: control
      readsfile1: SRR5860570_1.clean.fastq
      readsfile2: SRR5860570_2.clean.fastq
      source: NCBI
    - name: 10A
      paired: True
      path: FASTQs/2013/10A/
      experimental: selection
      readsfile1: 10A_BC15_F_TTAGGC_L006_R1_001.fastq
      readsfile2: 10A_BC15_F_TTAGGC_L006_R2_001.fastq
      source: EarlyJones2013
    - name: 10B
      paired: True
      path: FASTQs/2013/10B/
      experimental: selection
      readsfile1: 10B_BC15_F_TGACCA_L006_R1_001.fastq
      readsfile2: 10B_BC15_F_TGACCA_L006_R2_001.fastq
      source: EarlyJones2013
    - name: 17A
      paired: True
      path: FASTQs/2013/17A/
      experimental: selection
      readsfile1: 17A_BC15_F_CAGATC_L006_R1_001.fastq
      readsfile2: 17A_BC15_F_CAGATC_L006_R2_001.fastq
      source: EarlyJones2013
    - name: 17B
      paired: True
      path: FASTQs/2013/17B/
      experimental: selection
      readsfile1: 17B_BC15_F_ACTTGA_L006_R1_001.fastq
      readsfile2: 17B_BC15_F_ACTTGA_L006_R2_001.fastq
      source: EarlyJones2013
    - name: SRR303333
      paired: False
      path: FASTQs/2011/SRR303333/
      experimental: selection
      readsfile: SRR303333.fq
      source: EarlyJones2011
    - name: SECH1
      paired: True
      path: FASTQs/matuteSec/SECH1/
      species: drosophila sechellia
      readsfile1: SECH_1_1.fq
      readsfile2: SECH_1_2.fq
      source: matute
    - name: SECH2
      paired: True
      path: FASTQs/matuteSec/SECH2/
      species: drosophila sechellia
      readsfile1: SECH_2_1.fq
      readsfile2: SECH_2_2.fq
      source: matute
    - name: SECH3
      paired: True
      path: FASTQs/matuteSec/SECH3/
      species: drosophila sechellia
      readsfile1: SECH_3_1.fq
      readsfile2: SECH_3_2.fq
      source: matute
    - name: SECH4
      paired: True
      path: FASTQs/matuteSec/SECH4/
      species: drosophila sechellia
      readsfile1: SECH_4-sech_Anro_B5_TGACCA_L001_R1_001.fastq
      readsfile2: SECH_4-sech_Anro_B5_TGACCA_L001_R2_001.fastq
      source: matute
    - name: MD06m11d04y2010
      paired: True
      path: FASTQs/matuteSim/MD06m11d04y2010/
      species: drosophila simulans
      readsfile1: MD06_11_04_2010_54_R1_001.fastq
      readsfile2: MD06_11_04_2010_54_R2_001.fastq
      source: matute
    - name: MD199m12d10y2010
      paired: True
      path: FASTQs/matuteSim/MD199m12d10y2010/
      species: drosophila simulans
      readsfile1: MD199_12_10_2010_75_R1_001.fastq
      readsfile2: MD199_12_10_2010_75_R2_001.fastq
      source: matute
    - name: MD73m11d04y2010
      paired: True
      path: FASTQs/matuteSim/MD73m11d04y2010/
      species: drosophila simulans
      readsfile1: MD73_11_04_2010_54_R1_001.fastq
      readsfile2: MD73_11_04_2010_54_R2_001.fastq
      source: matute
    - name: NS79m03d07y2011
      paired: True
      path: FASTQs/matuteSim/NS79m03d07y2011/
      species: drosophila simulans
      readsfile1: NS79_03_07_2011_75_R1_001.fastq
      readsfile2: NS79_03_07_2011_75_R2_001.fastq
      source: matute


reference_genomes:
    - name: droSim1
      species: drosophila simulans
      path: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_simulans/droSim1.fa
      fai: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_simulans/droSim1.fa.fai
      source: UCSC Genome Browser
    - name: droSec1
      species: drosophila sechellia
      path: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_sechellia/droSec1.fa
      fai: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_sechellia/droSec1.fa.fai
      source: UCSC Genome Browser
    - name: dm6
      species: drosophila melanogaster
      path: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_melanogaster/dm6.fa
      fai: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_melanogaster/dm6.fa.fai
      source: UCSC Genome Browser


lift_genomes:
      dm6:
            droSec1: /proj/cdjones_lab/Genomics_Data_Commons/genomes/LiftOver/droSec1ToDm6.over.chain
            droSim1: /proj/cdjones_lab/Genomics_Data_Commons/genomes/LiftOver/droSim1ToDm6.over.chain

