data_sets:


    - name: Earley2011
      paired: False
      path: data/external/sequence/single_end/SRR303333/
      experimental: selection
      readsfile: SRR303333.fastq
      source: NCBI
      SRA: SRR303333
      pub: Earley2011
      subgroups: [all,selection,Earley2011,EarleyAll, cleanEarleyAll]

    - name: fragSimulated_dSim1
      paired: False
      subgroups: [none, simulated, fragsim1]
      readsfile: droSim1.L100.C5.E0.0.fastq
      source: erics fragmenter
      path: data/simulated/sequence/single_end/erics_fragmenter/
    - name: fragSimulated_dSec1
      paired: False
      subgroups: [none, simulated, fragsec1]
      readsfile: droSec1.L100.C5.E0.0.fastq
      source: erics fragmenter
      path: data/simulated/sequence/single_end/erics_fragmenter/


reference_genomes:
    - name: droSim1
      species: drosophila simulans
      path: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_simulans/droSim1.fa
      fai: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_simulans/droSim1.fa.fai
      source: UCSC Genome Browser
    - name: dm6
      species: drosophila melanogaster
      path: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_melanogaster/dm6.fa
      fai: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_melanogaster/dm6.fa.fai
      source: UCSC Genome Browser
    - name: droSec1
      species: drosophila sechellia
      path: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_sechellia/droSec1.fa
      fai: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_sechellia/droSec1.fa.fai
      source: UCSC Genome Browser


